# This workflows will test the SimNIBS examples in a Ubuntu machine

name: Run Examples
on: [push, pull_request]

jobs:
  run_simnibs_examples:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Miniconda
      uses: goanpeca/setup-miniconda@v1.6.0
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y octave
        conda create --file environment_linux.yml
        conda activate simnibs_env
        python setup.py install
        postinstall_simnibs -d . -s --no-extra-coils 
    - name: Run Examples Tests
      run: |
       source activate simnibs_env
       pytest simnibs/tests/examples/examples.py -v -s -x --junit-xml=test-results.xml
   
